name: testflight

on: [push]

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - uses: actions/cache@v1.0.3
        id: bundleCache
        with:
          path: vendor/bundle
          key: gem-${{ hashFiles(format('{0}{1}', github.workspace, '/Gemfile.lock')) }}
          restore-keys: gem-${{ hashFiles(format('{0}{1}', github.workspace, '/Gemfile.lock')) }}

      - name: bundle install
        if: steps.bundleCache.outputs.cache-hit != 'true'
        run: bundle install --path vendor/bundle

      - name: Setup SSH Keys and known_hosts for fastlane match
        env:
          PRIVATE_KEY: ${{ secrets.GITHUB_ACTIONS_SSH_PRIVATE_KEY }}
        run: |
          SSH_PATH="$HOME/.ssh"

          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"

          echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"

          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"

          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"

      - name: deploy
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        run: bundle exec fastlane deploy_testflight
